apiVersion: v1
kind: Service
metadata:
  name: meow
  labels:
    app: meow
spec:
  type: NodePort
  selector:
    app: meow
  ports:
  - protocol: TCP
    port: 8080
    name: meow

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: meow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: meow
    spec:
      containers:
      - name: meow
        image: huttermann-docker-local.jfrog.io/michaelhuettermann/alpine-tomcat7:VERSION
        ports:
        - containerPort: 8080